### ISSUE TITLE
Where to put --pec parameter?

### ISSUE THREAD

**Issue by stevo63** [nanopool/ewbf-miner#15]
I'm using EWBF miner with NHM.

**Comment by ChriscomIT** [comment]
Select settings then click Devices/Algorithms select your GPU then you click under algorithms on equihash(ewbf) and then you insert your parameter into the "Extra Launch Parameters" field right next to algorithms. Start mining again and you should be good.

**Comment by stevo63** [comment]
I already did it before i post. Problem is miner didn't even start. It was only change i had done.

**Comment by ChriscomIT** [comment]
Ok maybe try this mod as it work for me with it: https://github.com/gacopl/NiceHashMiner/releases

**Comment by stevo63** [comment]
I guess, i stay with Dillon fork,but i can point this issue and possible solution to him, thanks!
