### ISSUE TITLE
Still confused on where the source code is at?

### ISSUE THREAD

**Issue by Librebowski** [nanopool/ewbf-miner#73]
All I see is a "readme.md" maybe thats ok for some people but I wouldn't run this binary all willie nillie. -I would love to use this if you make the source code public but otherwise I am gonna have to keep it moving.

**Comment by mraaroncruz** [comment]
Take a look here https://github.com/nanopool/ewbf-miner/releases

They just are hosting the binaries, not the source.
Cheers

**Comment by Librebowski** [comment]
Thank you, my apologies now I understand whats what! -Cheers!

**Comment by mraaroncruz** [comment]
No problem. It's out of the ordinary. Enjoy
