### ISSUE TITLE
Configure EWBF to mine with only (gpu1 or 2) card?

### ISSUE THREAD

**Issue by charleshap** [nanopool/ewbf-miner#80]
So. This is my question.
 I have a gaming rig with a few card. But, it's a gaming rig. I would to be able to run GPU0 on its own instance and GPU1/2 on another. This way I can turn off mining on the main GPU while I game. Instead of shutting down the entire process. What command would I need to add to the config file to achieve this? Thanks

**Comment by longsh07** [comment]
This is exactly what I do. I have two GPU's running in separate instances of EWBF.

Are you using a config file? (There is an example one included in the zip.) If not, make sure to fill in all your pool/wallet details etc.

To select a specific GPU to mine with, look for the [common] heading in the .cfg file.
Under this is 'cuda_devices'. Set that to the number of the GPU you want to mine with. Save the .cfg as gpu0.cfg for example then repeat this for each GPU you want to use.

When you run the EWBF, call the config file by using miner.exe --config (path to .cfg). EWBF will tell you which card is selected/not selected at the start.

I have two batch files, GPU0 and GPU1 that call the respective gpu0.cfg and gpu1.cfg files and I just close the EWBF on my main GPU when gaming.

Hope that helps.

**Comment by charleshap** [comment]
TY , solved!!
